### ISSUE TITLE
training is slow

### ISSUE THREAD

**Issue by ws0352** [BarCodeReader/RCSB-PyTorch#1]
![image](https://user-images.githubusercontent.com/41601135/152717053-fbccc41d-fa27-49b3-9a69-43a62c22af50.png)
This is my GPU info, but it's slow when training.
![image](https://user-images.githubusercontent.com/41601135/152717174-5a9c8c6e-3980-4816-99de-3e90e414f5fb.png)

**Comment by BarCodeReader** [comment]
Hi, thanks for your interest in our work.

unfortunately, the training is slow, with 3090 we need a few days, it is because of the recurrent loop...

But as you can see from the evaluation results, the model converges very fast, in your case, the first epoch already get **MAE 0.034** on DUTSTE...

so you can reduce the epochs and in the meantime, we are about to optimize the code, and you are also welcome to contribute by submitting PRs.

cheers

**Comment by ws0352** [comment]
Thank you very much for your answer, I will continue to pay attention to your work, if necessary, I will contribute my part of the code.
